version: '3.8'
services:
  postgres_db:
    image: postgres:15
    container_name: kitaplik_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:7
    container_name: kitaplik_redis
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data: